import React from 'react';
import { View, Text, StyleSheet } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { DrawerContentScrollView, DrawerItemList } from '@react-navigation/drawer';

// This component defines the visual layout of the side menu
export default function CustomDrawerContent(props) {
  return (
    // A scrollable container to ensure all menu items are reachable on small screens
    <DrawerContentScrollView {...props}>
      {/* Branded header section at the top of the menu */}
      <View style={styles.header}>
        {/* App icon for a modern look */}
        <Ionicons name="rocket" size={40} color="#fff" />
        {/* App name displayed clearly */}
        <Text style={styles.headerText}>DDMI App</Text>
      </View>
      {/* Standard list of navigation links automatically generated by the Drawer */}
      <DrawerItemList {...props} />
    </DrawerContentScrollView>
  );
}

// Dedicated styles for the drawer's header
const styles = StyleSheet.create({
  header: {
    backgroundColor: '#007AFF', // Brand blue color
    padding: 20, // Spacing around the content
    alignItems: 'center', // Center elements horizontally
    marginBottom: 10, // Distance from the list of links
  },
  headerText: {
    color: '#fff', // White text for contrast against blue
    fontSize: 20, // Larger font for the app title
    fontWeight: 'bold', // Emphasize the app name
    marginTop: 10, // Space between the icon and the text
  },
});
